[package]
name = "fixity"
version = "0.1.0"
authors = ["Lee Olayvar <leeola@fastmail.com>"]
edition = "2018"

[features]
default = ["encoding_borsh"]
encoding_borsh = ["borsh"]
# An eventual cbor comparison encoding.
# encoding_cbor = []
# An eventual canonical json comparison encoding.
# encoding_json = []

[dependencies]
log = "0.4"
thiserror = "1.0"
blake3 = "0.3"
fastcdc = "1.0"
multibase = "0.8"
borsh = { version = "0.7", optional = true }

[dev-dependencies]
env_logger = "0.7"
maplit = "1.0"

[workspace]
members = [
  "fixi_cli",
]

