[package]
name = "fixity"
version = "0.1.0"
authors = ["Lee Olayvar <leeola@fastmail.com>"]
edition = "2018"

[features]
default = ["serialize_json"]
# An eventual series of alternate serialize for performance options.
#
# WARN: All of the canonical json libraries i've seen so far are in
# various states of abandon. This lib should not be trusted until we
# can fork and establish some trust.
serialize_json = ["serde", "cjson"]
serialize_cbor = ["serde", "serde_cbor"]
serialize_borsh = ["borsh"]
# An eventual cbor comparison encoding.

[dependencies]
log = "0.4"
thiserror = "1.0"
blake3 = "0.3"
fastcdc = "1.0"
multibase = "0.8"
borsh = { version = "0.7", optional = true }
serde_cbor = { version = "0.11", optional = true }
cjson= { version = "0.1", optional = true }
serde = { version = "1.0", optional = true, features = ["derive"] }

[dev-dependencies]
env_logger = "0.7"
maplit = "1.0"

[workspace]
members = [
  "fixi_cli",
  "fbuzhash",
]

