[package]
name = "fixi_cli"
version = "0.1.0"
authors = ["Lee Olayvar <leeola@fastmail.com>"]
edition = "2018"

[[bin]]
name = "fixi"
path = "src/bin/fixi.rs"

[features]
default = []
web = ["fixi_web", "fixi_web/structopt"]

[dependencies]
fixity = { path = ".." }
fixi_web = { optional = true, path = "../fixi_web" }
structopt = "0.3"
env_logger = "0.7"
tokio = "0.2"
