[package]
name = "fixity_kv"
version = "0.1.0"
authors = ["Lee Olayvar <leeola@fastmail.com>"]
edition = "2021"

[features]

[dependencies]
thiserror = "1.0"
async-trait = "0.1"
sled = { version = "0.34", optional = true }
tokio = { version = "1.4", features = ["io-util"] }
